---
- hosts: docker_box
  gather_facts: False

  vars:
    - root_dir: "{{ playbook_dir }}"
    - shared_dir: "{{ playbook_dir }}/../shared"

  pre_tasks:
    - debug: msg="Pre tasks section for {{ ansible_host }}"

    - set_fact:
        remote_ip_address: "{{ ansible_host }}"

    - include_vars: "defaults/main.yml"

    - name: ANSIBLE PYTHON | install fallback python if needed
      raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (apt -qqy update && apt install -qy python-minimal)
      become: yes

    - name: gather facts
      setup:

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      apt: pkg="acl"
      become: yes
      when: ansible_os_family == 'Debian'

    - name: Check for common pretasks
      local_action: stat path="{{ shared_dir }}/common_pretasks.yml"
      register: common_pretasks_exists
      tags: always

    - name: Include common pretasks
      include_tasks: "{{ shared_dir }}/common_pretasks.yml"
      when: common_pretasks_exists.stat.exists == true
      tags: always

  roles:
      - {
         role: "sa-python3",
         python_version: "{{ box_python3_version }}",
         tags: ["create", "sa_docker"],
         when: box_option_install_python3
        }
      - {
         role: "sa-docker",
         tags: ["create", "sa_docker"]
        }
  tasks:

    - debug: msg="Tasks section"

    - include_tasks: tasks/tasks_expose_tcp.yml
      when: (box_expose_tcp is defined) and box_expose_tcp
